name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: self-hosted
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}        
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push ttk
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          target: ttk
          push: true
          cache-from: type=registry,ref=ghcr.io/scivislab/ttk:buildcache
          cache-to:   type=registry,ref=ghcr.io/scivislab/ttk:buildcache,mode=max
          tags: |
            ghcr.io/scivislab/ttk:latest
      -
        name: Build and push ttk-dev
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          target: ttk-dev
          push: true
          tags: |
            ghcr.io/scivislab/ttk-dev:latest
          cache-from: type=registry,ref=ghcr.io/scivislab/ttk:buildcache
