name: ci

on:
  push:
    branches:
      - 'actions'

jobs:
  docker:
    runs-on: self-hosted
    strategy:
      matrix:
        ttk-version:
          - "dev"
          - "1.0.0"
      max-parallel: 1
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          build-args: |
            ttk=${{ matrix.ttk-version }}
          target: ttk
          push: true
          tags: |
            ghcr.io/scivislab/ttk:${{ matrix.ttk-version }}
          cache-from: type=registry,ref=ghcr.io/scivislab/ttk:buildcache
          cache-to:   type=registry,ref=ghcr.io/scivislab/ttk:buildcache,mode=max
